/* Auto-generated by genmsg_cpp for file /home/curiosul/ROS_Workspace/sandbox/roi/msg/IMU.msg */
#ifndef ROI_MESSAGE_IMU_H
#define ROI_MESSAGE_IMU_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "sensor_msgs/Imu.h"

namespace roi
{
template <class ContainerAllocator>
struct IMU_ {
  typedef IMU_<ContainerAllocator> Type;

  IMU_()
  : isValidIMU(false)
  , imu()
  {
  }

  IMU_(const ContainerAllocator& _alloc)
  : isValidIMU(false)
  , imu(_alloc)
  {
  }

  typedef uint8_t _isValidIMU_type;
  uint8_t isValidIMU;

  typedef  ::sensor_msgs::Imu_<ContainerAllocator>  _imu_type;
   ::sensor_msgs::Imu_<ContainerAllocator>  imu;


  typedef boost::shared_ptr< ::roi::IMU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roi::IMU_<ContainerAllocator>  const> ConstPtr;
}; // struct IMU
typedef  ::roi::IMU_<std::allocator<void> > IMU;

typedef boost::shared_ptr< ::roi::IMU> IMUPtr;
typedef boost::shared_ptr< ::roi::IMU const> IMUConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roi::IMU_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roi::IMU_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roi

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roi::IMU_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roi::IMU_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roi::IMU_<ContainerAllocator> > {
  static const char* value() 
  {
    return "897c65344524657282d14264e0b0dc3c";
  }

  static const char* value(const  ::roi::IMU_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x897c653445246572ULL;
  static const uint64_t static_value2 = 0x82d14264e0b0dc3cULL;
};

template<class ContainerAllocator>
struct DataType< ::roi::IMU_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roi/IMU";
  }

  static const char* value(const  ::roi::IMU_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roi::IMU_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#IMU Data, we may have to pass those infos too!\n\
\n\
bool isValidIMU\n\
sensor_msgs/Imu imu\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Imu\n\
# This is a message to hold data from an IMU (Inertial Measurement Unit)\n\
#\n\
# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n\
#\n\
# If the covariance of the measurement is known, it should be filled in (if all you know is the \n\
# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n\
# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n\
# data a covariance will have to be assumed or gotten from some other source\n\
#\n\
# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n\
# estimate), please set element 0 of the associated covariance matrix to -1\n\
# If you are interpreting this message, please check for a value of -1 in the first element of each \n\
# covariance matrix, and disregard the associated estimate.\n\
\n\
Header header\n\
\n\
geometry_msgs/Quaternion orientation\n\
float64[9] orientation_covariance # Row major about x, y, z axes\n\
\n\
geometry_msgs/Vector3 angular_velocity\n\
float64[9] angular_velocity_covariance # Row major about x, y, z axes\n\
\n\
geometry_msgs/Vector3 linear_acceleration\n\
float64[9] linear_acceleration_covariance # Row major x, y z \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::roi::IMU_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roi::IMU_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.isValidIMU);
    stream.next(m.imu);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct IMU_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roi::IMU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roi::IMU_<ContainerAllocator> & v) 
  {
    s << indent << "isValidIMU: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isValidIMU);
    s << indent << "imu: ";
s << std::endl;
    Printer< ::sensor_msgs::Imu_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROI_MESSAGE_IMU_H

